### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by parkouronit** [AnupKumarPanwar/Uber-Like-Cab-Service#3]
Can u please upload the database for this project?

**Comment by Tayeb-Ali** [comment]
you will find  many error  if you git them  help me  
and  this is  your database file  (y)

[id2200402_near_cabs.zip](https://github.com/AnupKumarPanwar/Uber-Like-Cab-Service/files/1584087/id2200402_near_cabs.zip)

**Comment by AnupKumarPanwar** [comment]
Yeah this is the database file.

**Comment by sinku252** [comment]
where is data base script ?

**Comment by Tayeb-Ali** [comment]
[DataBase](https://github.com/AnupKumarPanwar/Uber-Like-Cab-Service/issues/3#issuecomment-353722926)
