### ISSUE TITLE
Mysql DB script missing

### ISSUE THREAD

**Issue by sangramkokate** [AnupKumarPanwar/Uber-Like-Cab-Service#5]
Sir, Can you please upload the MySQL Database script?

**Comment by sinku252** [comment]
MySQL Database script?

**Comment by sangramkokate** [comment]
Yes..Got it from other issue..
I have already closed this issue.
.......
I have other problem regarding the book cab, please look into it.
https://github.com/AnupKumarPanwar/Uber-Like-Cab-Service/issues/6

Thanks.
